### ISSUE TITLE
Feature request: Focal point

### ISSUE THREAD

**Issue by poisa** [flyimg/flyimg#129]
I've worked in a closed-source version of a software that does pretty much the same as this. One very useful feature that it had was the ability to use an arbitrary point to crop an image to. In flyimg this is sort of achieved with the gravity parameter but it is not very precise. In the one I worked with you could specify an x and y focal point float that ranged from 0 to 1. 

In the context of my use case, this served two main purposes:

1. The user would upload an image and choose the focal point. No matter how we cropped the image, the "important" part (aka focal point) would always be in the center.
2. We ran some images through face detection and set the focal point automatically to the center of the face. Then, cropped profile pictures would always look great even if a user uploaded an image with a weird aspect ratio.

**Comment by baamenabar** [comment]
Yes! We are very aware of the limitations of gravity. We are reworking the whole cropping+resizing module to have more granular control and easier extensibility. I was precisely thinking about setting the focal point with 0 to 1 ranges for X and Y axis. I didn't have a name for it though. So expect this feature soon. Not next release, but probably the one after that.

Face detection integration will be much easier after we refactor the geometry module. And since we have face detection we can get not only profiles pictures generated, we can get group pictures "auto" cropped too, using the concentration of cages as gravity area. Although we don't have a timeline for that yet.

**Comment by bedoz** [comment]
Hello everyone, there's some update about this issue? Any timing info about 1.2 versione and it's milestone? Thank you very much

**Comment by sadok-f** [comment]
This is a very interesting Feature request, sorry it took us a while before reply to you.
To summarize it'll be great if we can add a smart-crop option which will focus on the most important part of an image for cropping.
For the face-detection part we can call it a smart-face-crop option.
@poisa Thanks again for this feature, we gonna work on it soon.
@bedoz Soon :)

**Comment by joshbrw** [comment]
I've had a play around with this library and the feature-set that you offer is absolutely amazing considering it is open source. Unfortunately without being able to do a crop with the face as the focal point it can't be considered in the same league as Cloudinary 😞 Are there still plans to add this feature in?

**Comment by sadok-f** [comment]
Hi @joshbrw,
Thank you for your interest in our project and your kind words about it.
Unfortunately, we didn't find a proper time to get around this issue and implement it.
I'll try my best to implement it asap.
Thank you again for your support!

**Comment by fhferreira** [comment]
+1 It will be awesome

**Comment by bedoz** [comment]
Yeah i want to renew my request to this feature...

**Comment by sadok-f** [comment]
Thank you for your message, I'm sorry regarding this delay.
This feature request will be a high priority and hopefully, we'll release it soon.

**Comment by fhferreira** [comment]
I have used the https://imagekit.io/ they have a good "Smart Crop"

**Comment by sadok-f** [comment]
We're happy to announce the release of the smart cropping feature: https://github.com/flyimg/flyimg#smart-crop
It would be great if you could test it out and provide feedback about it!
@fhferreira , @bedoz , @joshbrw 

Thank you All for your support and help!
