### ISSUE TITLE
Apache Setup

### ISSUE THREAD

**Issue by norvinjohn** [flyimg/flyimg#131]
Hi,

Can someone help me how can I this up to a standalone server with apache installed?

Thanks in advance :D

**Comment by baamenabar** [comment]
Hello, this project is not meant to be "uploadable", it's designed to be deployed as a docker container.

But, if you have Imagemagick in your server, you could try running the PHP app after converting the nginx config to an apache .htaccess config file. The nginx config is not in this repo, it's in the docker repo, chekc here: https://github.com/flyimg/docker-app/tree/master/resources/etc/nginx .

And even so, you would need to compile the Moz-Jpeg binaries yourself or not use them, by deactivating the moz-jpeg option in the config.

Even considering that, I'm not sure what other problems you could run into. 

But I have a tutorial on how to do a very easy setup in DigitalOcean http://code.medula.cl/article_Fly-image-microserver-with-Docker-on-Digitalocean.html give it a try.
