### ISSUE TITLE
Rotate image doesn't work

### ISSUE THREAD

**Issue by EtreRe** [flyimg/flyimg#137]
The rotate image option doesn't seem to work.

I have tried it on a local docker environnement with no succes and the example online have the same issue.

https://oi.flyimg.io/upload/r_-45,w_400,h_400/https://raw.githubusercontent.com/flyimg/flyimg/master/web/Rovinj-Croatia.jpg

![](https://oi.flyimg.io/upload/r_-45,w_400,h_400/https://raw.githubusercontent.com/flyimg/flyimg/master/web/Rovinj-Croatia.jpg)

**Comment by sadok-f** [comment]
Thank you for reporting this bug, we'll check it out asap.

**Comment by sadok-f** [comment]
Issue fixed with the latest release.
