### ISSUE TITLE
Background color doesn't work

### ISSUE THREAD

**Issue by EtreRe** [flyimg/flyimg#146]
The background color option doesn't seem to work.

I have tried it on a local docker environment with no success and the example online have the same issue.

https://oi.flyimg.io/upload/r_45,w_400,h_400,bg_red/https://raw.githubusercontent.com/flyimg/flyimg/master/web/Rovinj-Croatia.jpg

![](https://oi.flyimg.io/upload/r_45,w_400,h_400,bg_red/https://raw.githubusercontent.com/flyimg/flyimg/master/web/Rovinj-Croatia.jpg)

**Comment by sadok-f** [comment]
Thank you for submitting the issue, I'll close it due to the duplication.
see #145

**Comment by EtreRe** [comment]
Sorry for the duplicate !

**Comment by sadok-f** [comment]
no worries, we'll try to fix it asap.

**Comment by sadok-f** [comment]
Fixed in the latest release.
