### ISSUE TITLE
Signature Generation, undefined method named `getSecurityHandler`

### ISSUE THREAD

**Issue by gcoda** [flyimg/flyimg#155]
When i am trying to run:

     php app.php encrypt

I am getting

    Attempted to call an undefined method named 'getSecurityHandler' of class 'Core\Handler\ImageHandler'
    Did you mean to call 'securityHandler'?

Looks like this is really the fix, but i have zero experience with modern PHP, just `$app['image.handler']->SecurityHandler()` is enough?

As a side note, after writing comparable encrypt function in javascript i found something weird.
I needed to convert hashed key and vector to string hex and cut them. Is this expected?

```
const crypto = require('crypto')
const key = crypto.createHash('sha256').update('keykey').digest();
const ivHash = crypto.createHash('sha256').update('vectorvector').digest();
const iv = new Buffer.alloc(16, ivHash);

const newKey = key
  .toString('hex') // same data is twice the amount bytes now
  .substr(0, 32)   // and now we only have half of original hash

const newIv = iv.toString('hex').substr(0, 16) // iv was 16 bytes, now its 16 again but with less entropy

const cipher = crypto.createCipheriv('aes-256-cbc', newKey, newIv);
const data = cipher.update('w_900,h_200,c_1/https://m0.cl/t/resize-test_1920.jpg', 'utf-8', "base64");
const final = cipher.final("base64")
console.log(Buffer(data + final).toString('base64'))
```

**Comment by sadok-f** [comment]
Thank you for submitting the issue.
I identified the bug and it's in review now.

**Comment by sadok-f** [comment]
Fixed is pushed and merged.
Thank you again for reporting the bug, regarding the javascript implementation, I'm really not sure about it, maybe @baamenabar can check with you.
