### ISSUE TITLE
Rework the Documentation

### ISSUE THREAD

**Issue by sadok-f** [flyimg/flyimg#159]
The current documentation doesn't show properly all options available for the app.
We need to rewrite it in order to show all features available with a link to detailed MD file for each section such as Face Detection feature.
@baamenabar can you have a look :)

**Comment by ankush981** [comment]
Hello, I'd like to take this up, but am far from an expert-level PHP developer. Does that work?

**Comment by sadok-f** [comment]
Hi @ankush981 
yes sure, you can take it, you don't need that level to do this task.
All documentation exists but we need to organize it in order to show the important features in the main readme and move the small details to doc/ folder.
Could you please also take care of the example image used the in the main readme, we decided to replace it with this image and do the manipulation on it: 
http://medula.cl/t/cactus-flower.jpg

Thank you !

**Comment by ankush981** [comment]
Sure thing!
