### ISSUE TITLE
Output auto problem

### ISSUE THREAD

**Issue by martinbertinat** [flyimg/flyimg#169]
Hi all, first of all thanks for the great work.

I'm having problems with the auto output feature. If your input file is a jpg file, you navigate to the url to compress it in Chrome (for example) and then you save it to your disk and try to open it, you will see an error because the image is a webp and the extension is .jpg so the software in which you open the file is trying to open the image as .jpg and can't process it. I know this is not the main use case, but it is giving me problems with iphones

So, I try with the option "o_input" but I get another error:

Attempted to call an undefined method named "inputImageExtension" of class "Core\Entity\Image\OutputImage".
Did you mean to call "getOutputImageExtension"?

Clearly the method inputImageExtension is called and does not exist!

Let me know If I can fix this!

Thanks

**Comment by sadok-f** [comment]
Hi @martinbertinat !

Thank you for submitting the issue!

Regarding the error : `undefined method named "inputImageExtension"`
Obviously, it's a bug and we need to fix it, I assume it was introduced during the last changes we did (Code cleanup -_- by me).
We need to add a test for this case also. 

For the jpeg output which was generated as webp, I'll check that also.

If you want to help, you're welcome of course, the extension generation is done in `Entity/Image/OutputImage.php::generateFileExtension` function
