### ISSUE TITLE
Silex end of life => migrate to Symfony 4?

### ISSUE THREAD

**Issue by nickkraakman** [flyimg/flyimg#184]
Hi,

Would love to start using Flyimg, but the thing that is making us doubt is that June 2018 was the end-of-life of Silex, see message on the Silex homepage: [https://silex.symfony.com/](https://silex.symfony.com/).

They recommend to use Symfony 4 instead. Is there any plan to migrate Flyimg to Symfony 4?

Nick

**Comment by gplanchat** [comment]
Hello,

I have done it here : https://github.com/kiboko-labs/flyimg/tree/2.0.x-dev

The job started in #195, is almost finished at last, there are only some few things to finish : upgrade the documentation and finish removing superseded classes in [src/Core](https://github.com/kiboko-labs/flyimg/tree/2.0.x-dev/src/Core)
