### ISSUE TITLE
Extract s3 base domain into a config to use DigitalOcean Spaces or Minio

### ISSUE THREAD

**Issue by exfriend** [flyimg/flyimg#189]
Something along those lines

```
       $this->registerS3ServiceProvider($app, $s3Params);
        $app['flysystems']['file_path_resolver'] = function () use ($s3Params) {
            return sprintf('https://s3.%s.%s/%s/', $s3Params['region'], $s3Params['base_domain'], $s3Params['bucket_name']).'%s';
        };
```

**Comment by sadok-f** [comment]
@exfriend thanks for opening this issue.
I'm not sure if I get you right but if you wan to another storage provider such as `DigitalOcean Spaces` you should write a new `StorageProvide` class.
Flyimg uses FlySystem as storage provider and they have an Adapter for DigitalOcean:
https://flysystem.thephpleague.com/docs/adapter/digitalocean-spaces/

I hope this'll be helpfull!

**Comment by martinbertinat** [comment]
Hello! I'm needing the Digital Ocean Storage Provider too..

I know how to do it. It is almost the same as the S3 Adapter, but it is a little different here:

return sprintf('https://s3.%s.amazonaws.com/%s/', $s3Params['region'], $s3Params['bucket_name']).'%s';

I don't know much about Docker, so I don't really know how to start coding so for example: If my container stops I don't want to loose anything!

Can anyone guide me a bit?

Thank you and as you see English is not my primary language.

**Comment by sadok-f** [comment]
Hi @martinbertinat ,

Thank you for your request, the DigitalOcean API are compatible with those of S3, from Flysystem’s perspective this means you can use the league/flysystem-aws-s3-v3 adapter.
so you can change, the storage_system option in parameters.yml and you put the necessary credentials for DO.

**Comment by martinbertinat** [comment]
Hello @sadok-f . 

Yes I know they are compatible but Digital ocean requires an 'endpoint' parameter, please see my fork: https://github.com/martinbertinat/flyimg/blob/master/src/Core/StorageProvider/S3StorageProvider.php#L50

In line 33  I have to change to not say anything related to amazon. https://github.com/martinbertinat/flyimg/blob/master/src/Core/StorageProvider/S3StorageProvider.php#L33

Thanks

**Comment by ahmadalli** [comment]
is there any way to fix it?

**Comment by jonathanlundstrom** [comment]
I've also created a PR that attempts to solve this by adding support for the `endpoint` parameter. Hopefully this can be tested soon by the maintainer and merged to the base repository. https://github.com/flyimg/flyimg/pull/409

**Comment by sadok-f** [comment]
Hey @jonathanlundstrom,

Thank you for submitting the PR, I'll check it out asap.
