### ISSUE TITLE
Proxy pass with NGINX

### ISSUE THREAD

**Issue by yoldar** [flyimg/flyimg#190]
Hi! Thank you for that great tool!

I have a question. I'm using Flyimg as microservice as a part of docker-compose.yml. I have one global nginx which routes to each microservice. Flyimg is under /image-optimizer/ path. Here is global nginx config:
```
location /image-optimizer/ {
    proxy_pass http://image-optimizer:80/;
}
```

The problem is when global proxy passes something like 
`http://test.test/image-optimizer/upload/w_500,h_500,q_90/https://m0.cl/t/butterfly-3000.jpg `
it removes double slash from https://

nginx logs from flyimg show this:
`"GET /upload/w_500,h_500,q_90/https:/m0.cl/t/butterfly-3000.jpg HTTP/1.0" 500`

I now that this question is related to nginx community but you are more in context :)

May be you could give an advise?

**Comment by baamenabar** [comment]
@yoldar . can you share a bit more of your nginx config? My quick guess is something else in that config might be stripping the slashes. 

But first try adding: `merge_slashes off` above the `proxy_pass` line. 

I don´t expect it to solve the problem, but we might get lucky.

**Comment by sadok-f** [comment]
Thank you @yoldar for submitting the issue!

Well our demo website is running on nginx as proxy pass to a docker container.
Here the config:
```
server {
    server_name oi.flyimg.io;

    location / {
        proxy_pass http://localhost:8080;
    }
}
```

As suggetion maybe if try to remove the tail slash in your config to become:
```
location /image-optimizer/ {
    proxy_pass http://image-optimizer:80;
}
```

**Comment by sadok-f** [comment]
@yoldar I just reproduce the issue with Nginx, adding the trailing slash cause removing the double slash.
So remove the trailing slash and it'll work!

**Comment by yoldar** [comment]
Thank you all for your replies!

While debugging this issue I have learned how to correctly write nginx rewrite regex rules :)

Solution is here:
```
location /image-optimizer/ {
    rewrite  ^/image-optimizer/upload/(.*)/(http:|https:)/(.*)  /upload/$1/$2//$3 break;
    proxy_pass http://image-optimizer:80;
}
```

**Comment by sadok-f** [comment]
Great to know that you fixed it!
Thank you again for contributing with us!
