### ISSUE TITLE
Image path parameters is ignored

### ISSUE THREAD

**Issue by yoldar** [flyimg/flyimg#191]
Hi guys!

Is that possible to not ignore image path parameters?

When I try this in container:
`curl "http://localhost/upload/w_500,h_500,q_90/http://some.com/uploads/image.jpg?token=342342342334&someParam=dlklksfdldf`

I got error:
> Error occurred while trying to read the file Url : http://some.com/uploads/image.jpg

Download image in container with regular wget works normal.
> wget http://some.com/uploads/image.jpg?token=342342342334&someParam=dlklksfdldf is ok

P.s. I really need this because downloading images can only be with access params like token and so on.

**Comment by yoldar** [comment]
> Hi @yoldar !
> 
> The problem is with `?` which will convert the token into a parameter GET in the flyimg application, maybe if you try to encode it before pass it to flyimg server:
> 
> `curl "http://localhost/upload/w_500,h_500,q_90/http://some.com/uploads/image.jpg%3Ftoken=342342342334`

Thanks!

**Comment by yoldar** [comment]
@sadok-f 

Could you please advice is that possible to ignore all parameters when making hash naming for original and optimized files? I mean original-HASH than stored under "tmp" folder and HASH.webp under "uploads" folder?

P.s. Because access token changes every time but image still the same.

**Comment by sadok-f** [comment]
@yoldar Thanks for pointing this out, in fact, the original image should be saved without considering any extras arguments, so the hash should be generated only with the image source URL.
I'll work on it this weekend and hopefully submit a PR regarding that!

Thank you again!

**Comment by yoldar** [comment]
Thanks! It would be great!
P.s. Open source rulez! 😁

**Comment by sadok-f** [comment]
Here we go
