### ISSUE TITLE
Question about clearing cache

### ISSUE THREAD

**Issue by yoldar** [flyimg/flyimg#192]
Hi again :)

I'm using Flyimg as image optimizer for picture gallery. Original images are stored on other micro-service. When user opens image gallery, frontend app changes src of images to Flyimg service. As you can understand Flyimg do not used as original image storage. It used as image optimizer to minimize traffic which send to user.

My question is: Is it normal to periodically clean folders(/var/www/html/web/uploads and /var/www/html/var/tmp) items to free space and to not let container itself growth in volume?

P.s. I have binded that folder to host already
```
volumes:
      - ./volumes/image-optimizer/uploads:/var/www/html/web/uploads:rw
      - ./volumes/image-optimizer/var:/var/www/html/var:rw
```

P.s.p.s. I mean "rm -rf" by for example crontab.

**Comment by sadok-f** [comment]
Hi @yoldar !

You can of course clear up the 2 folders `var/tmp` and `web/uploads`, Flyimg has to fetch the original image again and generate a new requested one.
