### ISSUE TITLE
Separate Auto Lossy and Lossless

### ISSUE THREAD

**Issue by TiKevin83** [flyimg/flyimg#199]
Right now a source png image will only be compressed in auto output mode if the browser supports webp, otherwise it will stay as a png.  It would be useful either to have separate auto lossy and auto lossless output modes to change the fallback order to webp->jpg->png, or to have the auto output mode choose a fallback order depending on the presence and value of the quality setting (that is, if a user asks for q_85 assume that they want auto lossy mode).

**Comment by baamenabar** [comment]
Hello @TiKevin83 ! that's a quite useful use case. 
I'll add it to 1.2 milestone
thanks for the feedback
