### ISSUE TITLE
Missing User-Agent header to get images

### ISSUE THREAD

**Issue by sadok-f** [flyimg/flyimg#200]
Some servers denied flyimg app to download the image because of missing User-Agent header.
A solution is to add this header to the InputImage::saveToTemporaryFile() function.

**Comment by baamenabar** [comment]
What UA should we choose? 
maybe some servers will give out different image format based on the UA sent

**Comment by sadok-f** [comment]
the one worked is this option:
'header' => 'User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201',
but I'd like to make it optional and configurable via the parameters.yml file
