### ISSUE TITLE
Feature request: Direct upload endpoint

### ISSUE THREAD

**Issue by roman-vohnik** [flyimg/flyimg#209]
Hi, first of all - thanks for the great work on this project.

Flyimg is made for image manipulations + serving cached images. But what about new option = to use flyimg only for image manipulations like API service? There can be route / endpoint for direct upload of image in raw format (maybe base64 encoded in POST data). Then source images does not have to be public and downloaded from flyimg. Even works from localhost when developing.

All of this is because our different approach. We have flyimg on separate server as a service and main servers background jobs (in queue) are calling flyimg and saving result images to our storage which is served by our nginx on different domain.

Sounds good to you? 

I have a working prototype, but I am not so familiar with silex / symfony. It is something like:
```
public function fooAction(string $options): Response
    {
		$request = Request::createFromGlobals();

		$encodedImage = $request->get('image');

		if ($encodedImage === null || strlen($encodedImage) === 0) {
			$this->response->setStatusCode(500, 'Missing "image" in post data');
		} else {
			$inputImage = base64_decode($encodedImage);

			$filename = TMP_DIR . uniqid('/post-original-', true);
			file_put_contents($filename, $inputImage);

			$outputImage = $this->imageHandler()->processImage($options, $filename);

			$this->response->generateImageResponse($outputImage);

			unlink($filename);
		}

        return $this->response;
    }
```

**Comment by sadok-f** [comment]
Hi @roman-vohnik!
Thank you very much for your request (sorry for this late response), it sounds interesting for us as well.
As I understand for you, you already implement it in your servers?
if you don't mind you can create a PR and we'll review it and check it out.

We'd love to include more people as contributors!

Thank you again!
