### ISSUE TITLE
How to specify a default domain name?

### ISSUE THREAD

**Issue by ztj1993** [flyimg/flyimg#211]
Suppose I have an image storage server with the domain name `img.com`.

How can I access it:
`http://localhost:8080/upload/w_200,h_200,c_1/file.jpg`
Match to:
`http://img.com/file.jpg`

---

Suppose I have a configuration template

```
d_a: aaa.com
d_b: bbb.com
```

Is it accessible:
`http://localhost:8080/upload/w_200,h_200,c_1/d_a/file.jpg`
Is it possible to automatically match domain names?

---

Just some suggestions. The above content comes from software translation.

**Comment by sadok-f** [comment]
Hi @ztj1993 ,

Thank you for opening the issue!
Currently, Flyimg app doesn't support dynamic domain matching.
if you want to get images from domain `img.com`
you'll have to access it from:
`http://localhost:8080/upload/w_200,h_200,c_1/http://img.com/file.jpg`

**Comment by ztj1993** [comment]
Temporarily processed with nginx
