### ISSUE TITLE
Create transformations API

### ISSUE THREAD

**Issue by baamenabar** [flyimg/flyimg#22]
The idea is to return a URL to the resource instead of an image.
Consider the case where the resource has been uploaded to s3 maybe give the amazon URL. 
This may be configurable according to the storage selected.

**Comment by sadok-f** [comment]
This is done in the latest release, we should add the proper documentation.
by specify the `path` route instead of upload, it return the full url to the resource:
`http://localhost:8080/path/w_200,h_200,c_1/Rovinj-Croatia.jpg`

**Comment by baamenabar** [comment]
the original intent of this is done, I'll close it.
I'll be opening a new bug soon revisiting the subject from another use case.
