### ISSUE TITLE
Update the dockerfile to use the latest base image 1.1.0

### ISSUE THREAD

**Issue by sadok-f** [flyimg/flyimg#229]
Update the dockerfile to use the latest base image 1.1.0 which uses s6 overlay instead of supervisord.

**Comment by bull0n** [comment]
Still available? Can I take it? :)

**Comment by sadok-f** [comment]
@bull0n sorry I just pushed the PR for this one, there's another issue for Hacktoberfest label, if you want to take it

**Comment by bull0n** [comment]
@sadok-f No problem. I'll check it!
