### ISSUE TITLE
Make a helpful root page.

### ISSUE THREAD

**Issue by baamenabar** [flyimg/flyimg#23]
Currently we only have a text that says "hello from docker"
Maybe make this a submodule project?

**Comment by sadok-f** [comment]
Could be an upload form with transformation inputs?

**Comment by baamenabar** [comment]
It would have to be simple. And here I worry about security.

**Comment by baamenabar** [comment]
# Proposal for content in root page:

<img src="https://raw.githubusercontent.com/flyimg/graphic-assets/master/logo/raster/flyimg-logo-rgb.png" width="300">

## Hello from Flyimg
### The image above (logo) has been served using flyimg.

how? Calling the source in the `<img>` like this:
```
http://oi.flyimg.io/upload/w_300/http://m0.cl/t/flyimg-logo-rgb.png
```
It got transformed from the original file which was 6000px wide!

Now, on the server, there is a cached version of this transformed image. There is no need to do the  transformation again next time someone requests this image.

The best of all is that you get *Moz-jpeg* compression by default on all your JPEGs.

## Transformations

You can do many different transformations to you images, like: *quality*, *face-crop*, *face-blur*, *width, *height*, *crop*, *background*, *rotate*, *scale*, amongst many others. 

[Check the docs for more info](https://github.com/flyimg/flyimg).

Happy imaging!
