### ISSUE TITLE
slash error 

### ISSUE THREAD

**Issue by fyher** [flyimg/flyimg#235]
i have this
Error occurred while trying to read the file Url : https:/raw.githubusercontent.com/flyimg/graphic-assets/master/logo/raster/flyimg-logo-rgb.png

but I test /upload/w_300/https://raw.githubusercontent.com/flyimg/graphic-assets/master/logo/raster/flyimg-logo-rgb.png

thanks

**Comment by sadok-f** [comment]
Hi @fyher 
Thank you for reporting the issue.
Could you please specifiy more details about it?

**Comment by fyher** [comment]
I don't know , I have the docker image, it's work on server A , i install it on server B and now I have this bug.  I send https://raw.githubusercontent.com/flyimg/graphic-assets/master/logo/raster/flyimg-logo-rgb.png and the code receive just http::/ , is delete one slash 

i have open the code and is nos good, I add str_replace("http:/","http://"...) and its work :(

**Comment by fyher** [comment]
you can see it here http://flyimg.nolohi.fr and http://flyimg.nolohi.fr/upload/w_300/https://raw.githubusercontent.com/flyimg/graphic-assets/master/logo/raster/flyimg-logo-rgb.png

**Comment by sadok-f** [comment]
how is the configuration for the server B ? 
I mean in `http://flyimg.nolohi.fr` your run Flyimg behind a reverse proxy? can you past here the configuration?

**Comment by fyher** [comment]
is the same config for the server A , 
the docker config 
  flyimg:
    image: flyimg/flyimg-build
    restart: always
    ports:
      - 8089:80
    networks:
      noholi:
        aliases:
          - flyimagenolohi.com

**Comment by sadok-f** [comment]
I mean the reverse proxy behind your domain http://flyimg.nolohi.fr
since access directly the running container: http://flyimg.nolohi.fr:8089/upload/w_300/https://raw.githubusercontent.com/flyimg/graphic-assets/master/logo/raster/flyimg-logo-rgb.png
is working perfectly.
So it should be something in the reverse proxy that redirects the traffic to the container on port 8089

**Comment by fyher** [comment]
the conf 
<VirtualHost *:80>
    ServerName flyimg.nolohi.fr
CustomLog /var/log/apache2/secure_access.log combined

<Proxy *>
Allow from 127.0.0.1
</Proxy>
ProxyPreserveHost On
ProxyPass / http://127.0.0.1:8089/
ProxyPassReverse / http://127.0.0.1:8089/
ProxyRequests Off
</VirtualHost>

**Comment by sadok-f** [comment]
Sorry for my late response, honestly it looks an issue from the apache configuration which remove the double slash, you can play with configuration and try to find out where it happens.
but isn't from the Flyimg code source.

**Comment by HagenMorano** [comment]
Ran into the same problem on nginx. Fixed by adding `merge_slashes off;` to nginx config.

**Comment by sadok-f** [comment]
Hi @fyher 
I'm wondering if you still use Flyimg in your company/organisation ?
If so, it would be great if you could add your entry here in the Adoperts file
https://github.com/flyimg/flyimg/blob/main/ADOPTERS.md
many thanks!
