### ISSUE TITLE
FaceDetect not working

### ISSUE THREAD

**Issue by seebeen** [flyimg/flyimg#236]
Hello,

All of the facedetect functions aren't working. Face crop, blur etc... My deployed version isn't changing the image, and the demo images on project page here on github show all blurred faces.

**Comment by seebeen** [comment]
4) Tests\Core\Processor\ExtractProcessorTest::testExecuteSuccess
Failed asserting that 0.00019847725233884358 matches expected 0.
5) Tests\Core\Processor\FaceDetectProcessorTest::testProcessFaceCropping
Failed asserting that 0.24950044141447522 matches expected 0.
6) Tests\Core\Processor\FaceDetectProcessorTest::testProcessFaceBlurring
Failed asserting that 0.0031502127020878183 matches expected 0.

**Comment by sadok-f** [comment]
Hi @seebeen,

Thank you for reporting the issue, we'll investigate it and check it out.

Best,
Sadok

**Comment by sadok-f** [comment]
Hi @seebeen could you please test with the latest release 1.1.5 ?

Thank you :)

**Comment by seebeen** [comment]
Works like a charm. Thanks man!

**Comment by sadok-f** [comment]
Hi @seebeen 
I'm wondering if you still use Flyimg in your company/organisation ?
If so, it would be great if you could add your entry here in the Adoperts file
https://github.com/flyimg/flyimg/blob/main/ADOPTERS.md
many thanks!
