### ISSUE TITLE
Question - I'm adding support for PDF's and Movies in a fork

### ISSUE THREAD

**Issue by louisl** [flyimg/flyimg#241]
Thanks for the repo, it's good work.

I'm working on a fork of this to support PDF's and movie files, are you interested in a PR for it or would you rather me keep it separate?

PDF support (ghostscript) is almost done. It has one new param to choose a page number.

Movie support (ffmpeg) - not started yet. I'm planning to add a param to choose the time mark for to take the image from.

**Comment by sadok-f** [comment]
Hi @louisl !

Many thanks for supporting Flyimg project, we'd love to have your new features in our project.

Please create a PR for each feature and we'll be happy to review it and have you in our contributors list.

**Comment by louisl** [comment]
Hi @sadok-f 

As I needed to change things in the same files for both features I closed one PR and did one PR for both features. I did it in a way that wouldn't break backwards compatibility and the changes are fairly minimal. I guess the install of ghostscript and ffmpeg could be optional depending if people wanted these features.

The movie file for tests I got from https://www.sample-videos.com and the pdf I made from a Pages template so no copyright issues.

I'll be putting this in a staging environment for one of my jobs Monday would be nice if it makes it into the core project.

Let me know what you think.

**Comment by sadok-f** [comment]
Hi @louisl !
Thank you for your contribution to Flyimg!
I'm gonna keep the issue open until the link in the documentation got fixed.
For the video you can use the direct link `https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_2mb.mp4` instead of `https://m0.cl/t/SampleVideo_1280x720_2mb.mp4`
Same for the PDF

**Comment by louisl** [comment]
You're welcome, thanks for the project and your help with the PR.

I'll make the changes to the README, to use the video link, we need to find a hosted PDF or alternatively host the one I made for the tests somewhere. Any suggestions?

**Comment by sadok-f** [comment]
I uploaded them to flyimg.io server:
- https://oi.flyimg.io/lighthouses.pdf
- https://oi.flyimg.io/big_buck_bunny_720p_2mb.mp4

**Comment by louisl** [comment]
Both are failing for some reason. I'm out of time right now, will look later tonight.

https://oi.flyimg.io/upload/w_200,h_200,pg_1/https://oi.flyimg.io/lighthouses.pdf
https://oi.flyimg.io/upload/w_200,h_200,tm_00:00:05/https://oi.flyimg.io/big_buck_bunny_720p_2mb.mp4

(https://github.com/louisl/flyimg/tree/feature/update-readme)

**Comment by sadok-f** [comment]
My bad I didn't update the docker image on the server, just did now.
It works perfectly!

**Comment by louisl** [comment]
No problem, PR #247 should complete this. Thanks agin for your help.

**Comment by sadok-f** [comment]
Closing the issue.
Thank you @louisl for the great work!
