### ISSUE TITLE
Input image url with query string

### ISSUE THREAD

**Issue by Checkumeito** [flyimg/flyimg#255]
Hello,

Currently, flyimg ignore the query string of the input image URL. This cause problem for some image files being hosted at some provider that relies on the query string to serve newer / updated cached version.

Clearing the flyimg local cache or force refresh does not work as the image is cached at source, and served with query string.

**Comment by sadok-f** [comment]
Hi @Checkumeito,

Thank you for opening this issue, could you please provide more information about the issue, with examples will be really helpful.

Thank you again !

Sadok

**Comment by Checkumeito** [comment]
Hello,

I upload image _A_ to the provider, the provider give me the filename which:

`http://theme.hstatic.net/1000366282/1000553011/14/mobile_6_image.jpg`

Then I run through my flyimg to resize it down to my liking.
I change my mind and replace image _A_ with image _B_, They give me another URL: with a query string 

`http://theme.hstatic.net/1000366282/1000553011/14/mobile_6_image.jpg?v=3`

This display image _B_ correctly.

However, the original URL still display image _A_ because the provider hasn't invalidated their edge cache yet.

When I run the URL with the query string into my flying, the image _A_ still appears. I believe flyimg did not process the URL with the query string being used as cache busting/versioning.

Does my explanation make sense? The links I give you are a real example but it may not be accurate as the provider may invalidate the cache at any time.

**Comment by sadok-f** [comment]
Hi @Checkumeito,
Thank you very much for providing those details, I'll work on it asap.
(Sorry for the late reply, been busy all this period)

**Comment by visioncode** [comment]
@sadok-f same issue here. I need to get my source images via a PHP script which includes the path, e.g. example.com/files?path=logos/microsoft.jpg .. unfortunately it results in a convert error. I figured out that the query string must be the problem. Any quickfix available?

**Comment by sadok-f** [comment]
Hi @visioncode , thanks for bringing up again this issue.
I'll try to work on fixing it and get back to you.

**Comment by sadok-f** [comment]
Hi @visioncode,
did youtry to encode the image path? 
something like `http://localhost:8080/upload/w_200/http://example.com%2Ffiles%3Fpath%3Dlogos%2Fmicrosoft.jpg` ?

**Comment by nicolas-albert** [comment]
I cannot get it work:
`https://dummyimage.com/200x300?text=so%20good`
vs
`https://demo.flyimg.io/upload/w_200,q_90/https://dummyimage.com/200x300?text=so%20good`
Query string is ignored.

**Comment by sadok-f** [comment]
Hi @nicolas-albert 
Thank you for reporting this issue, I'll check it out.

**Comment by sadok-f** [comment]
Hi @nicolas-albert , did you try to URL encode from `?` onward? like this 
```
https://demo.flyimg.io/upload/w_200,q_90/https://dummyimage.com/200x300%3Ftext%3Dso%20good
```
I've tested it on a local server with the following format and it did work:
```
https://demo.flyimg.io/upload/r_10,rf_1,q_20/http://host.docker.internal:5000/get_image%3Fshow%3Dtrue
```

**Comment by nicolas-albert** [comment]
Ok, it's work. The query part is ignored for the cache entry, if I change the size, it's ok: [https://demo.flyimg.io/upload/w_200,q_90/https://dummyimage.com/201x300%3Ftext%3Dso%20good6](https://demo.flyimg.io/upload/w_200,q_90/https://dummyimage.com/201x300%3Ftext%3Dso%20good6)

**Comment by sadok-f** [comment]
yes can refresh the image when adding the param `rf_1` to the URL options.
I'm gonna close the issue.
thank you again !
