### ISSUE TITLE
Specify a cache validator

### ISSUE THREAD

**Issue by pakdoz** [flyimg/flyimg#261]
Reports from GTMetrix say resources from Flyimg are missing a cache validator. Resources that do not specify a cache validator cannot be refreshed efficiently. Specify a Last-Modified or ETag header to enable cache validation. Any advice to fix it?

**Comment by sadok-f** [comment]
hey @pakdoz ,

Thank you for submitting this issue and sorry for this late response.
I'll take a closer look into it and check if I can add those options: Last-Modified and ETag
(sorry didn't work in Flying code base for a while)
