### ISSUE TITLE
question about query parameters

### ISSUE THREAD

**Issue by rafipiccolo** [flyimg/flyimg#264]
Hello all, I have a pure question, not a bug.

Is there any technical reason for not using query parameters to pass settings ? Is it only a cosmetic choice ?

i mean this :
https://www.myservice.io/upload/w_333,h_333,q_90/https://m0.cl/t/butterfly-3000.jpg

could have been :
https://www.myservice.io/generate?w=333&h=333&q=90&src=https://m0.cl/t/butterfly-3000.jpg

**Comment by sadok-f** [comment]
Hi @rafipiccolo ,

Thank you for your question.

isn't only a cosmetic choice but also technical, the upload route composed of 2 parameters:
- `options` which is the list of options to pass to the image processor handler, in your example it is `w_333,h_333,q_90`
- `imageSrc` which is the URL to the source image `https://m0.cl/t/butterfly-3000.jpg`

Passing the whole options as one parameter (with customized delimiter) make it easier to manipulate those options and merge them with their default values as well.

If you have a special use case why do you need such a route, please provide us with more information.

Thank you again!

Best,
Sadok

**Comment by rafipiccolo** [comment]
Okay i see it has some advantages : smaller url, ez parsing.
Thanks for the reply,
