### ISSUE TITLE
Google Cloud Run Restricting Source Domains

### ISSUE THREAD

**Issue by sjorritsma** [flyimg/flyimg#307]
Just installed Flyimg on Google Cloud Run. This is my first Google Server impressed with the performance.

How can I change the restricted source domains?

According to the documentation its in the config/parameters.yml but I can't find that.

**Comment by sadok-f** [comment]
Hi @sjorritsma ,

Thank you for opening this issue, we're happy to hear about using Google Run!

Regarding the restricted source domains, yes it is inside the file `config/parameters.yml` , you need to change the parameter `restricted_domains` to `true` and under that, you add your list of authorized domains under `restricted_domains `.

```
# restrict domains, false by default
restricted_domains: true

# if restricted_domains is enabled, put whitelist domains here
whitelist_domains:
    - domain-1.com
    - domain-2.com
 ```

**Comment by sjorritsma** [comment]
Thank you for your answer. But where can I find the config/parameters.yml? 

Do you know the path to the directory. When I do a find / -name "parameters.yml" I can't find it. 

![Screenshot 2021-03-17 111830](https://user-images.githubusercontent.com/11626737/111452158-870efe80-8712-11eb-99dd-e8ff27ed9e2f.jpg)

**Comment by sadok-f** [comment]
@sjorritsma, not sure if you could have access to the running container in Google Run.
anyway, if you want to modify something inside the running container, you have to clone the repo, do the changes , build a new image and push it to your Google Container Registry, and then tell google run to use the new image.

**Comment by sjorritsma** [comment]
Thx that was the trick I needed. 

Made a Fork of FLYIMG in github, edit the file config/parameters.yml 

Pushed the button in my Fork :  
![image](https://user-images.githubusercontent.com/11626737/111483613-3ceb4480-8735-11eb-8573-7ced7171ab3d.png)

Under 5 minutes running image server.

**Comment by sadok-f** [comment]
Great!

**Comment by sadok-f** [comment]
Hi @sjorritsma 
I'm wondering if you still use Flyimg in your company/organisation ?
If so, it would be great if you could add your entry here in the Adoperts file
https://github.com/flyimg/flyimg/blob/main/ADOPTERS.md
many thanks!
