### ISSUE TITLE
URLs with redirects are broken?

### ISSUE THREAD

**Issue by GitBoudewijn** [flyimg/flyimg#310]
Hey, great application, but I've come across something that's broken. See for example:

- https://oi.flyimg.io/upload/w_100/https://i.imgur.com/NmZp3hB.jpg
- https://oi.flyimg.io/upload/w_100/https://imgur.com/NmZp3hB.jpg

The first one works fine but the second one gives an error, even though it's the exact same image (https://imgur.com/NmZp3hB.jpg just redirects to https://i.imgur.com/NmZp3hB.jpg).

**Comment by sadok-f** [comment]
Hey @GitBoudewijn ,

Thank you raising this issue, I'll check it out and back to you asap.

Best

**Comment by sadok-f** [comment]
@GitBoudewijn  issue fixed with latest release, please update your code and happy Flyimging !
