### ISSUE TITLE
Add Akeneo adapter

### ISSUE THREAD

**Issue by Philippe-M** [flyimg/flyimg#318]
Hello,

It's possible to add a Akeneo adapter ?

https://github.com/kiboko-labs/flyimg/tree/master/src/Akeneo

thank's for advance.

**Comment by sadok-f** [comment]
Hey @Philippe-M 
Thank you for opening this issue, could you please provide more details about the new adapter?
if you have something already up and running maybe you can create a PR to add it to Flyimg.

**Comment by Philippe-M** [comment]
Hey @sadok-f

[Akeneo](https://www.akeneo.com) is a PIM, it offers an API to be able to use it with other applications.

For example I use it from Excel by VBA code which queries Akeneo by the API, in return I get a url corresponding to the high definition image, then I pass this url to Flyimg which allows me to generate an embeddable image low definition on the fly and at the right dimension in Excel. 

Unfortunately I do not master the development well enough to offer a PR.

There is this fork https://github.com/kiboko-labs/flyimg of Flyimg which integrates Akeneo but it seems to be based on an old version.

**Comment by sadok-f** [comment]
Hi @Philippe-M 
I'm wondering if you still use Flyimg in your company/organisation ?
If so, it would be great if you could add your entry here in the Adoperts file
https://github.com/flyimg/flyimg/blob/main/ADOPTERS.md
many thanks!
