### ISSUE TITLE
How can we secure our custom hosted Flyimg client on Google Cloud Run

### ISSUE THREAD

**Issue by virendrao** [flyimg/flyimg#324]
We have hosted Flyimg service on Google Cloud run, all works fine. However we would like say to process request coming only from our domain say abc.net or www.abc.net ?

P.S. I am not talking about image source domain.

**Comment by sadok-f** [comment]
Hi @virendrao,
Many thanks for the issue you opened.
Unfortunately we don't have an implementation to filter the incoming requests.
Maybe you can implement that on the Google Cloud side? I saw a couple of documentation about setting up an external HTTP(S) load balancer in front of Google Cloud Run where you can filter by ip.

**Comment by virendrao** [comment]
Hey thanks buddy. I tried to host it on ElasticBeanStalk as well which worked using steps provided using composer and CLI.

But when I try to put it behind AWS API Gateway as Request Parameter, Gateway basically considers "path separator (/)" which are part of image Source Path as special character I guess and doesn't forward to EB.

Do we have support for Query Parameters ? With Query parameters we should be able to pass HTTP Image Source, rather than Request Parameters.

**Comment by sadok-f** [comment]
Even if you try to encode the image URL parameter? 
such as `https%3A%2F%2Fraw.githubusercontent.com%2Fflyimg%2Fgraphic-assets%2Fmaster%2Flogo%2Fraster%2Fflyimg-logo-rgb.png`

**Comment by sadok-f** [comment]
Hi @virendrao 
I'm wondering if you still use Flyimg in your company/organisation ?
If so, it would be great if you could add your entry here in the Adoperts file
https://github.com/flyimg/flyimg/blob/main/ADOPTERS.md
many thanks!
