### ISSUE TITLE
502 Gateway Timeout on first image hit

### ISSUE THREAD

**Issue by NiteshOswal** [flyimg/flyimg#328]
We're consistently seeing an issue where the first hit to an image results in a 502. But, waiting for a few seconds and refreshing the URL returns the image. Is this in any way related to how images are cached, or should we add a fallback for such sitautions.

Any clues are appreciated.

**Comment by sadok-f** [comment]
Hi @NiteshOswal ,
thanks for opening this issue.
could you please provide more details about the issue? reproducible steps would help us identify the root causes.

**Comment by sadok-f** [comment]
Closed for inactivity
