### ISSUE TITLE
Is it possible to support the amd64 architecture?

### ISSUE THREAD

**Issue by baptiste313** [flyimg/flyimg#329]
Hello, I would like to know if there is a way to support flyimg on amd64 architecture to be compatible with the Raspberry Pi?

Because I have this error when I try to use the Docker image :

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Thanks in advance 👍

**Comment by baptiste313** [comment]
I found a solution on [Reddit](https://www.reddit.com/r/docker/comments/ray2wc/), here are the two commands to use flyimg on Raspberry Pi :
```bash
docker run --privileged --rm tonistiigi/binfmt --install all
```
```bash
docker run -itd -p 8080:80 --platform linux/amd64 flyimg/flyimg-build
```

**Comment by sadok-f** [comment]
Hello @baptiste313!

Thank you for opening this issue!
if the solution you found worked for you?
