### ISSUE TITLE
image rotating when I dont want it to

### ISSUE THREAD

**Issue by srsquare** [flyimg/flyimg#332]
I have some images that display correctly when loaded directly in the browser but are being rotated when I rezie using w_ q_. I am assuming the exif data in some of my images is wrong. Anyway was wondering if there was a way to prevent rotation when the image is resized. So far in my limited experiments flying is quite cool :) Thanks.

**Comment by sadok-f** [comment]
Hi @srsquare ,
thanks for reporting your issue and your feedback!
is it possible to provide an example image?

**Comment by srsquare** [comment]
https://oi.flyimg.io/upload/w_600,q_80/ ... JackAttacked-Feb2021/IMG_20210215_003758.jpg

when I load the image directly its fine, but when passed through flying its upside down... I fixed it directly by rotating the img 90 degrees, saving it, rotating it back, and saving, and then it (among others) were fine. I just would like a way to tell flyimg not to rotate...

![IMG_20210215_003758](https://user-images.githubusercontent.com/12405211/169738746-20b350e2-1b90-4464-9a93-03fcc33e70ba.jpg)
n

**Comment by sadok-f** [comment]
Hi @srsquare,
it seems your image contains metadata and Rotation information, and imagemagik uses that information.
to get around this issue, I've added a new option called `auto-orient`, you can add it to the flying URL options as `ao_1`
Please update your repo and give it a try.
