### ISSUE TITLE
Transparency in PNG image turns black, when setting output to JPG

### ISSUE THREAD

**Issue by jeroenbach** [flyimg/flyimg#334]
We're using PNG images with transparent backgrounds, but in some cases we want the transparent background to become white. When changing the output to JPG the transparency is removed, but it becomes black, even when setting the background to white.

I've added our used PNG here:
![shirt](https://user-images.githubusercontent.com/6712714/169973384-843003f8-8dac-4456-8db7-76c2ea99172a.jpg)
And then when I change the output to JPG (and for the example rotated the image 45 degrees), I get this picture:
![da04de3369eec7aca4783b01dc146b7c](https://user-images.githubusercontent.com/6712714/169973496-8f870f27-5b4e-41e0-a38d-2d8c2fbf0b6d.jpeg)
Here you see the transparency is black and then the background behind the black is white (because I rotated the image)

**Comment by sadok-f** [comment]
Thank you @jeroenbach for reporting this issue!
Please update your repo to the latest version, it should be fixed!
