### ISSUE TITLE
The controller for URI "/" is not callable: Identifier "flysystems" is not defined.

### ISSUE THREAD

**Issue by uzairwp** [flyimg/flyimg#342]
how can we implement BunnyCDN storage? I tested multiple repositories and all of them gave the error "Identifier "flysystems" is not defined."?

[flysystem bunny storage](https://github.com/PlatformCommunity/flysystem-bunnycdn )
[flysystem adaptor 2](https://github.com/tinect/bunnycdn-s3-flysystem2-adapter)

**Comment by uzairwp** [comment]
> Hi @uzairwp
> 
> thanks for opening this issue.
> 
> how you tried to implement the BunnyCDN storage? you should follow one of the StorageProvider implementations here: https://github.com/flyimg/flyimg/tree/main/src/Core/StorageProvider
> 
> if you did that already, maybe you can share the code.
> 
> thanks!

**Argument 1 passed to PlatformCommunity\Flysystem\BunnyCDN\BunnyCDNAdapter::__construct() must be an instance of PlatformCommunity\Flysystem\BunnyCDN\BunnyCDNClient, null given**



```
class bunnystorage implements ServiceProviderInterface
{

  
   public function register(Container $app)
    {
        $bunnycdn = new BunnyCDNAdapter(
    new BunnyCDNClient(
        'flyimg', 
        'myapi', 
        BunnyCDNRegion::NEW_YORK
    )
);

        $app->register(
            new FlysystemServiceProvider(),
            [
                'flysystem.filesystems' => [
                    'storage_handler' => [
                        'adapter' => 'PlatformCommunity\Flysystem\BunnyCDN\BunnyCDNAdapter',
          
                        'args' => [$bunny],
                    ],
                ],
            ]
        );

        return $app;
    }
}


```

**Comment by sadok-f** [comment]
Can you try this code:

```
class bunnystorage implements ServiceProviderInterface
{

  
   public function register(Container $app)
    {
        $bunny = new BunnyCDNClient(
          'flyimg', 
          'myapi', 
           BunnyCDNRegion::NEW_YORK
          );

        $app->register(
            new FlysystemServiceProvider(),
            [
                'flysystem.filesystems' => [
                    'storage_handler' => [
                        'adapter' => 'PlatformCommunity\Flysystem\BunnyCDN\BunnyCDNAdapter',
          
                        'args' => [$bunny],
                    ],
                ],
            ]
        );

        return $app;
    }
}
```

**Comment by uzairwp** [comment]
Thanks. works fine. but in that case, we can't use CDN pull zone. is there any way to use cdn with flyimg?

**Comment by sadok-f** [comment]
Assuming the issue was fixed.
