### ISSUE TITLE
Excuse me, how to clear the disk cache, or set the cache size expiration time.

### ISSUE THREAD

**Issue by saicbs** [flyimg/flyimg#375]
Or just output to the browser without caching to disk, I'm controlling the cache through things like Nginx.

**Comment by sadok-f** [comment]
Hi @saicbs Thank you for opening this issue!
Currently Flyimg doesn't support this feature, it might be an option to disable caching to disk and serve directly the generated image.
is this what you're looking for? we could work on it for the next release.

**Comment by saicbs** [comment]
Thank you for your response, yes, I need the feature to disable writing to the cache and directly output the image.

**Comment by sadok-f** [comment]
Hi @saicbs,
a new option to disable the cache (writing generated images to disk) was released in the latest release https://github.com/flyimg/flyimg/releases/tag/1.2.3
in config/parameters.yml file you can edit the option `disable_cache` to `true`
Please test it out and let me know if it works as needed.
