### ISSUE TITLE
error on face-functions

### ISSUE THREAD

**Issue by tribor** [flyimg/flyimg#412]
###  version tested

- **1.3.1** (docker image flyimg/flyimg-build)
- also noticable on [demo.flyimg.io](https://demo.flyimg.io/)

###  what I am trying to do
use the function "faceblur" (or other face-functions)

###  how to reproduce
tested with photo of a [group](https://windeurope.org/wp-content/uploads/images/about-us/WindEurope-board-members.jpg) but every photo will work to reproduce 

* run docker image and open: http://0.0.0.0:8080/upload/fb_1/https://windeurope.org/wp-content/uploads/images/about-us/WindEurope-board-members.jpg
* or use 
https://demo.flyimg.io/upload/fb_1/https://windeurope.org/wp-content/uploads/images/about-us/WindEurope-board-members.jpg

###  error description
web-UI reports:
> Whoops, looks like something went wrong.

docker logs:
```
Message: Command failed.
The exit code: facedetect: error: cannot load input image /var/www/html/var/tmp/5da8bbd2eaa4dc93c35b659a1db78b9f.avif
The last line of output: /usr/local/bin/facedetect /var/www/html/var/tmp/5da8bbd2eaa4dc93c35b659a1db78b9f.avif
File: /var/www/html/src/Core/Processor/Processor.php
Line: 54
Trace: #0 /var/www/html/src/Core/Processor/FaceDetectProcessor.php(58): Core\Processor\Processor->execute(Object(Core\Entity\Command))
#1 /var/www/html/src/Core/Handler/ImageHandler.php(146): Core\Processor\FaceDetectProcessor->blurFaces(Object(Core\Entity\Image\OutputImage))
#2 /var/www/html/src/Core/Handler/ImageHandler.php(173): Core\Handler\ImageHandler->faceDetectionProcess(Object(Core\Entity\Image\OutputImage))
#3 /var/www/html/src/Core/Handler/ImageHandler.php(108): Core\Handler\ImageHandler->processNewImage(Object(Core\Entity\Image\OutputImage))
#4 /var/www/html/src/Core/Controller/DefaultController.php(26): Core\Handler\ImageHandler->processImage('fb_1', 'https://windeur...')
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(169): Core\Controller\DefaultController->uploadAction('fb_1', 'https://windeur...')
#6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 /var/www/html/web/index.php(4): Silex\Application->run()
#10 {main}
```

when I download the image in the container and the run `facedetect` it seems to work:
```
root@7d54de0dd44e:~# facedetect  WindEurope-board-members.jpg
1720 181 81 81
822 212 83 83
111 251 81 81
1009 253 81 81
631 258 82 82
1204 270 82 82
1387 270 85 85
```
note: an older version 1.1.42 does work without showing this error

**Comment by sadok-f** [comment]
Thank you @tribor for opening this issue and for the detailed explanation!
it seems related to the AVIF format which became the default output since v1.3.0, if you add the output parameter to be jpg or png the FaceBlur works as expected.
I'll look into this issue, thank you for reporting it
