### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by VictorGrycuk** [flyimg/flyimg#414]
Hi, I would like to know if you plan to support Arm devices. I would love to run it on my Raspberry Pi.

Thanks!

**Comment by sadok-f** [comment]
Hi @VictorGrycuk,

Thank you for bringing this up, we're working on it and we'll update the docker images accordingly.

**Comment by VictorGrycuk** [comment]
Awesome, thanks!

**Comment by sadok-f** [comment]
@VictorGrycuk 
can you try out the latest docker image? 
`flyimg/flyimg-build:latest` or `flyimg/flyimg-build:1.3.3`

thx

**Comment by sadok-f** [comment]
interesting, leet me add the linux/arm64/v8 platform then.

**Comment by sadok-f** [comment]
ok, can you try thew new version `flyimg/flyimg-build:1.3.4` ?

**Comment by VictorGrycuk** [comment]
Thanks @sadok-f, but I am getting the same issue. Trying to build the image locally, I get the following:
```bash
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected
host platform (linux/arm64/v8) and no specific platform was requested
```

By specifying the platform, I get
```bash
image with reference flyimg/base-image:1.4.1 was found but does not match the specified platform:
wanted linux/arm64, actual: linux/amd64
```

I'll keep troubleshooting it after work.

**Comment by sadok-f** [comment]
yes, I need to add the multi-arch build to the base image as well, I'll keep you posted.

**Comment by sadok-f** [comment]
quick update here, I'm still trying to build the base image with multi-arch, still blocked by many dependencies

**Comment by sadok-f** [comment]
Sorry for the delay here, I'm facing some issues compiling/installing some libraries in the base image for ARM, especially the pip AVIF library.
I'll add more details in the issue I opened in the base-image repo https://github.com/flyimg/base-image/issues/18
any help is appreciated.

**Comment by sadok-f** [comment]
Hi @VictorGrycuk , can you try out the latest version 1.3.5?
The base image got updated with a successful build for the arm arch, unfortunately the face detection for avid format will not work, you have to disable avif generation when using fave detection option.
Thanks

**Comment by VictorGrycuk** [comment]
@sadok-f Apologies for the late response.
I just tried the new image, and I was able to run it on the raspberry!

**Comment by sadok-f** [comment]
Great, thank you for confirming
