### ISSUE TITLE
Benchmarks clarification request

### ISSUE THREAD

**Issue by peraronsson** [flyimg/flyimg#427]
Hello, just a few questions regarding the [benchmarks]( https://github.com/imgproxy/imgproxy/blob/master/BENCHMARK.md):

- **Latencies**: does this mean "response time per request"? (which is what I want to know)
- **Bytes Out**: this is always zero, so I guess it's some sort of bug?
- **Test Image**: what is the original size of `Rovinj-Croatia.jpg`?

I'm trying to understand where Flyimg would be in [this comparison](https://github.com/imgproxy/imgproxy/blob/master/BENCHMARK.md#results).

**Comment by sadok-f** [comment]
Hello @peraronsson 
Thank you for opening this issue!
the actual benchmark in the Flyimg repo is outdated, I think it's a good idea to update it and maybe use the Apache `ab` tool.
regarding your questions:
- yes the Latencies mean the response time per request
- BytesOut is the number of sent bytes in the HTTP body (From vegeta tool [documentation](https://github.com/tsenart/vegeta))
- `Rovinj-Croatia.jpg` Original size is 57.3 KB

Actually I'll update the benchmark script to use `ab` tool to have a meaningful comparison with the other tools you mentioned.

**Comment by sadok-f** [comment]
@peraronsson  can you check the latest benchmark I just released?
https://github.com/flyimg/flyimg/blob/main/docs/full-documentation.md#benchmark

**Comment by peraronsson** [comment]
> @peraronsson can you check the latest benchmark I just released? https://github.com/flyimg/flyimg/blob/main/docs/full-documentation.md#benchmark

This looks really good, and thank you so much for doing this!  😃 
If I understand the results correctly, Flyimg is a lot more performant than the "competitors" in the table. Do you agree?
The only thing I am missing now is a url to the image used for the test, for reference, and for running my own tests.

**Comment by sadok-f** [comment]
actually yes I used the same image in the benchmark script to resize it to 500x500.
But the source of the image is local (the benchmark script downloads it and then deletes it).
I'm not sure about other solutions, it seems some of them are using a local version as well.

**Comment by sadok-f** [comment]
hey @peraronsson , 
I'm going to close this issue if any help is still needed please feel free to comment and I'll open it.
Thank you again!
