### ISSUE TITLE
Parameters.yml file not working

### ISSUE THREAD

**Issue by Joonas12334** [flyimg/flyimg#449]
When using docker to map parameters.yml file it just won't be read.

I'm using this docker compose file:

version: '3.8'

services:
  flyimg:
    image: flyimg/flyimg
    container_name: flyimg-container 
    ports:
      - "8087:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - /volume1/docker/flyimg/parameters.yml:/var/www/html/config/parameters.yml 
    restart: unless-stopped

**Comment by Joonas12334** [comment]
Update: The file does work. Partially at least. Found out from the log files that the heic_speed variable works well. It's the options_separator that's giving me a headache. That's the whole error code on website when changing separator to "+" for example "Error while leading the generated image." I'm lost.

**Comment by Joonas12334** [comment]
Log file: https://nas.alphabetfilms.eu/sharing/1ihIKjDFP

**Comment by sadok-f** [comment]
Hi @Joonas12334 
Thank you for reporting this issue, I'll investigate it and get back to you asap.

**Comment by sadok-f** [comment]
Hello @Joonas12334 again,

can you share the full URL parameters that you use when you switch to using `+` as `options_separator` ?
this URL for example works as expected:
`upload/rf_1+q_95+w_600/https://picsum.photos/200`

**Comment by Joonas12334** [comment]
I'm using quality and width. For eg i would want to use `https://url/upload/q_70+w_4000/https://url/wp-content/uploads/2024/05/IMGL1271.jpg` as i intend to use it as cdn for wordpress then the default "," splits the url rendering link incorrect.

**Comment by Joonas12334** [comment]
Indeed, it does work when i'm setting the address manually. I guess i was just confused that the flyimg "homepage" stopped working with custom options as that still used "," for the options_seperator.

**Comment by sadok-f** [comment]
let me check then the homepage code, probably the comma separator is hardcoded within the JS code.

**Comment by sadok-f** [comment]
Thank you @Joonas12334 for reporting this issue 👍 
I've updated the js code to add a new variable called `OPTIONS_SEPARATOR` in `web/js/main.js` that needs to be changed when changing `options_separator` in `config/parameters.yml`
see PR #451
