### ISSUE TITLE
Update the repo description

### ISSUE THREAD

**Issue by baamenabar** [flyimg/flyimg#46]
how a bout this?

> A Dockerized PHP Microservice application to resize and crop images on the fly. Get optimized images with MozJPEG, WebP or PNG using ImageMagick to do Face detection, cropping, Face Blurring, Rotation and many other options. Runs inside a Docker container for easy to deployment. Abstract storage based on FlySystem in order to store images on any provider (local, S3,...).

**Comment by baamenabar** [comment]
and this?

> A Dockerized Microservice, a PHP application to resize and crop images on the fly. Get optimised images with MozJPEG, WebP or PNG using ImageMagick. Includes face detection, cropping, face blurring, image rotation and many other options. Abstract storage based on FlySystem in order to store images on any provider (local, AWS S3...).

**Comment by sadok-f** [comment]
Awesome! Go for it

**Comment by baamenabar** [comment]
Done
