### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by jvzaniolo** [flyimg/flyimg#466]
# Broken Images

Sorry for the short title, I really don't have a clue what's happening.

Sometimes an image is cut in half and a gray box appear in the background.

I can fix the image using the `rf_1` option, but I would like to understand what's happening.

![image](https://github.com/flyimg/flyimg/assets/54036572/2ec62438-8de2-4239-b9ee-dd72e913f437)

**Comment by sadok-f** [comment]
Hi @jvzaniolo 
thank you for reporting this issue.
can you share more details about your setup?
which version of Flyimg are you using?
can you paste the endpoint here? 

for the image with the gray box, can you past here the full URL of it?

thanks!

**Comment by jvzaniolo** [comment]
We're using the latest Docker image `"flyimg/flyimg:latest"`  
The endpoint: https://img.beuni.com.br
And the broken image URL: https://img.beuni.com.br/upload/w_400,h_400,o_webp/https://proxy.beuni.com.br/api/images/products/rec2IHRZ6otqa8NCK-attyUE2bO6tH55GSI.webp

This `proxy.beuni.com.br` thing is a node.js application to fetch the image from AWS S3.

We're migrating our images from Airtable* to AWS S3, so if the image can't be found on S3 we download it from Airtable and then upload it to S3 using AWS SDK `lib-storage`

```js
const upload = new Upload({
  client: s3client,
  params: {
    Bucket: 'beuni-proxy-images',
    Key: objectKey,
    Body: await fetch(image.url).then((res) => res.blob()),
  },
});
```

The next time the client requests the same image, it should be available on S3 on this URL https://beuni-proxy-images.s3.amazonaws.com/{IMAGE_NAME}

To respond the image, we're sending the blob response:

```js
const imageResponse = await fetch(url);
const imageBlob = await imageResponse.blob();
const contentType = imageResponse.headers.get('content-type') || '';
return new Response(imageBlob, {
  headers: {
    'Content-Type': contentType,
    'Cache-Control': 'public, max-age=86400, s-maxage=86400, immutable',
  },
});
```

I'm sure this could easily be something wrong on our end, but we tried requesting the image directly from our Node.js app and the image returns as expected.
Also, when running with the `rf_1` option, it works too.

Thanks for the quick response!

*Airtable is a low-code database. It shouldn't host our images, that's why we're trying to migrate them

**Comment by sadok-f** [comment]
why is the source image [https://proxy.beuni.com.br/api/images/products/rec2IHRZ6otqa8NCK-attyUE2bO6tH55GSI.webp](https://img.beuni.com.br/upload/w_400,h_400,o_webp/https://proxy.beuni.com.br/api/images/products/rec2IHRZ6otqa8NCK-attyUE2bO6tH55GSI.webp)
has a `Content-Type: image/jpeg` but the extension is webp?
did you try the output jpeg format `o_ jpg` ?

**Comment by jvzaniolo** [comment]
Yeah, this was an internal issue.
We were searching for the image with `.wepb` on S3 Bucket but the image was really `.jpeg`. The URL is dynamically generated.

Changing the output format to `o_jpg` works, but I'm concern that's creating another cache entry instead of fixing the problem.
Is it possible to change the image format with Flyimg? Or am I suppose to set `o_ ` to the image original type?

**Comment by sadok-f** [comment]
for AVIF and WebP formats, you can disable them in the config file by setting:

```yaml
enable_avif: false
enable_webp: false
```

also Flyimg can support S3 as a storage layer, so if you have another storage endpoint, Flyimg can fetch the image and store it in s3, unfortunately it doesn't support folder structuring.

**Comment by jvzaniolo** [comment]
I need to search for the image in two different tables on our database so we're running a node app to search for the image and store it in S3. Do you think Flyimg could do that for me?

I'll try to disable AVIF and WebP formats

**Comment by sadok-f** [comment]
Flyimg can handle a custom logic for the storage, but it doesn't do that for fetching the source images.
you can keep your node app to search for the images and return the endpoint, and use the S3 storage option in Flyimg to store the generated images there.

**Comment by sadok-f** [comment]
hi @jvzaniolo 
any update on this issue? can we close it?

**Comment by jvzaniolo** [comment]
Sorry I didn't get back to you sooner, some other things came as a priority.
I'll mark it as closed because we haven't had a similar issue since we stopped converting images to .webp, so that may be the issue.
