### ISSUE TITLE
HTTP Status Code Responses

### ISSUE THREAD

**Issue by TimWeyand** [flyimg/flyimg#488]
We currently are trying flyimg for a project of ours. In our Usecase it is helpful to have explicit Exceptions for different Errors and also deliver different HTTP Response Codes. 

For Example - if the origin "reports" file not found, we would like that flyimg is reporting the same http code (404). Same for restricted access on the origin (403), ...

Is that something which could be interesting for the project and we should send a pull request as we finish? Or out of scope?

**Comment by sadok-f** [comment]
Thank you @TimWeyand.
yes definitely, it would be great if you could work on PR to add such implementation.
