### ISSUE TITLE
Add overlays functionality, like text on top of the image, or any graphic.

### ISSUE THREAD

**Issue by baamenabar** [flyimg/flyimg#49]
Consider using phantomJS to load a URL, render it, and return a part or all of the rendered page. 

The part that would be selected should be passed as a css selector in the first parameter.

Something like this:

`http://flyimg.io/render/.header__title--big/https://some .webpage.com`

**Comment by baamenabar** [comment]
I'm thinking this could be it's own service in it's own container that we can call. Specially since the environment for phantomJS is node. Actually we should be using headless chrome for this nowdays.

**Comment by sadok-f** [comment]
I think there are 2 differents features here we're talking about:
- Generating an image from given URL and css selector: this could be done in its own service.
- Adding an Overlay (text) on a top of an image (with given position): this is a very nice feature that we need to work on it asap.

**Comment by baamenabar** [comment]
The thing with the overlay text is the control, there is two to work with text.

1. Somehow put some text with some font over an image given some coordinates: *EASY* (even with imagemagick)
2. Put a specific text, with specific font-size, with specific glyph rendering with specific font (not always available with hinting), with specific line-height, color, transparency, alignment, text wrapping, with a specific letter-spacing and word spacing with glyph alternates: *PRACTICALLY IMPOSSIBLE* (it is already quite complicated with CSS).

Option 1 is good for an amateur photographer who wants to put their name in an image, or maybe a simple meme generator.

Option 2 is what a stakeholder (PM, designer, boss, ...) wants when they thing about overlaying text on an image.

Option 2 is doable using a browser and CSS and saving the rendered piece as a bitmap.

**Comment by baamenabar** [comment]
I leave this link here, because this and similar projects have addressed the issue in depth.

https://github.com/cheeaun/puppetron
