### ISSUE TITLE
Save images in readable paths

### ISSUE THREAD

**Issue by adiltibari** [flyimg/flyimg#519]
Is there a way to make flyimg save images that are being optimized on a readable path?

so if the image url is :
https://cdn.test.com/upload/q_56/https://demo.net/storage/app/public/product/2024-07-03-6685bab14071f.png

it will save it to : 
demo.net(folder)/storage(folder)/app(folder)/public(folder)/product(folder)/2024-07-03-6685bab14071f.png

**Comment by sadok-f** [comment]
Thank you @adiltibari for opening this issue!
If I get you right, you want to change the location where the generated images are being stored?

if yes, is the new path a fixed path? 

currently the images are stored in the `upload` folder under the public folder web.
if you want to change that, to a fixed path, you need to create the desired path:
```sh
mkdir -p web/storage/app/public/product
```
and then change the `UPLOAD_WEB_DIR` constant to `'storage/app/public/product/'` in the constants.php file

to get the image path, you need to call the path endpoint.
example:

https://cdn.test.com/upload/q_56/https://demo.net/storage/app/public/product/2024-07-03-6685bab14071f.png

Call the path endpoint:

https://cdn.test.com/path/q_56/https://demo.net/storage/app/public/product/2024-07-03-6685bab14071f.png

the image is available under 
`https://cdn.test.com/storage/app/public/product/4eaf3878f10741f3cc1c9809131f961b.png`


I hope I make it clear

**Comment by sadok-f** [comment]
I see, unfortunately Flyimg doesn't support that.
