### ISSUE TITLE
incorrect version shown in footer

### ISSUE THREAD

**Issue by francescor** [flyimg/flyimg#528]
**Describe the bug**
footer legend with flyimg version shows wrong release

**To Reproduce**

Deploy with  `image: flyimg/flyimg:1.4.14` and footer shows: `Version: 1.4.13` as in https://flyimg-qa.opencityitalia.it/ right now

![image](https://github.com/user-attachments/assets/e0ee6d35-a831-4891-9fbb-da295f94aeac)

**Environment setup:**
docker swarm

**Comment by sadok-f** [comment]
Thank you for reporting this issue @francescor 
fixed in the latest release
