### ISSUE TITLE
more detailed debug

### ISSUE THREAD

**Issue by francescor** [flyimg/flyimg#530]
**Is your feature request related to a problem? Please describe.**
When, with debug enabled I have an error, like 
```
The last line of output: /usr/local/bin/magick /var/www/html/var/tmp/original-6389adcca4323fcff74797f28cc46b45 -thumbnail '400'x'400''>' -colorspace 'sRGB'  -filter 'Lanczos' -strip TGA:- | '/opt/mozjpeg/cjpeg' -quality '90' -outfile '/var/www/html/var/tmp/31f7418869ea7339838fd90fa1801249-671141c8ccea10.57797112.jpg' -targa 

The exit code: Unsupported Targa colormap format
```
We are unable to spot the source image that cause the issue (we believe are images like [this one](https://flyimg.opencityitalia.it/upload/rf_1,o_auto,w_2500,h_2500/https%3A%2F%2Fs3-eu-west-1.amazonaws.com%2Fstatic.opencity.opencontent.it%2Fvar%2Fpisa%2Fstorage%2Fimages%2F3330-2-ita-IT%2FHomepage_header_logo.png) but only with some browser's setup )

**Describe the solution you'd like**

We would like to have a more detailed debug with a link to the source image

Best would be more backup level, like: debug/info/error

**Comment by sadok-f** [comment]
@francescor In the latest release [1.5.0](https://github.com/flyimg/flyimg/releases/tag/1.5.0), I've added new logging using the monolog library. The output should be more readable and contain more information about the Request.
Also a new variable was added to control the log level `log_level: error # possible values: debug, info, error...`
