### ISSUE TITLE
add the ability to resizes images directory

### ISSUE THREAD

**Issue by dimanovoseltsev** [flyimg/flyimg#54]
I would like to be able to resize mode with servo skuchevaya not it.

for example
https://dimains.com/upload/w_300,h_200/imagefolder/12541.jpg

in the current documentation is not seen as an opportunity to implement resize or tell me how to do it?

**Comment by baamenabar** [comment]
Thanks for posting an issue.
I'm not understanding the question though. What do you mean by 
> servo skuchevaya not it

?

What your example path will do is: try to get the resource from the server's path  `./imagefolder/12541.jpg`  resize the image if it's there an serve it.

**Comment by sadok-f** [comment]
Yes that part is missing in the docs, we'll update it soon.
In your case you should create the folder `imagefolder` inside the web directory:
`web/imagefolder`
