### ISSUE TITLE
Evaluate Switching License to AGPL to Protect SaaS Use Cases

### ISSUE THREAD

**Issue by sadok-f** [flyimg/flyimg#546]
Currently, our project is licensed under MIT. While this license provides significant freedom for users and encourages adoption, it also allows third parties to use the project in SaaS (Software as a Service) offerings without contributing back any modifications or improvements.

**Problem Statement:**
Under the current license:

Companies can use the project to build proprietary SaaS products.
Modifications made for these SaaS offerings are not required to be shared, limiting community benefits.
This creates a potential "freeloading" scenario where others profit from the project without contributing back to its sustainability or growth.

**Proposed Solution:**
Switching to the GNU Affero General Public License (AGPL) would address these concerns.
The key benefits of adopting the AGPL include:

**SaaS Loophole Closure:**
The AGPL requires that if the software is used to provide a service over a network (e.g., SaaS), the source code of the modified version must be made available to users of that service.

**Encourages Contributions:**
Organizations using the software in a SaaS model would be required to contribute their improvements, leading to a stronger and more innovative community.

**Prevents Vendor Lock-In:**
Users of SaaS offerings based on this project will always have access to the source code, including any modifications, reducing the risk of being locked into a proprietary version.

**Promotes Open Source Ethics:**
The AGPL aligns with our goal of maintaining a transparent and open ecosystem where both individuals and companies benefit fairly from the project's development.

**Comment by lorello** [comment]
We are a company and we are quite happy with flyimg. When needed, we have contributed a new feature to the source code. I think the AGPL license promotes this kind of behavior, so I would be happy if this license was adopted.
