### ISSUE TITLE
Support for -m and -mt flags with Cwebp 

### ISSUE THREAD

**Issue by vikobeibe** [flyimg/flyimg#547]
Flyimg seems to use Cwebp which offers the `-mt` flag for multithreading, and the `-m` flag with values ranging `0` to `6` for making tradeoffs between speed and file size. I have found that combining the two with a reasonable `-quality` setting could speed up encodes up to 2.5x times in my testing setup when compared to not having the flags set. I propose these to be added.

**Comment by sadok-f** [comment]
Thank you @vikobeibe for suggesting these options.
I think it's a good idea to add the `-mt` flag to the base command for converting to Webp format (the wrapper for ImageMagick would be `-define webp:thread-level=1`).
Regarding the method flag (`-m`), it seems the default value is `4`, we can add another URL variable to set this value, it could be `webpm_3` for example, what do you think?

**Comment by vikobeibe** [comment]
Sorry for the slow response. Yes this sounds great, thank you!

**Comment by sadok-f** [comment]
@vikobeibe checkout the latest release [1.7.1](https://github.com/flyimg/flyimg/releases/tag/1.7.1) that add the support for the 
-m and -mt flags.
Thank you for your feature request!

**Comment by sadok-f** [comment]
Hi @vikobeibe 
If your company/organisation is using Flyimg, it would be great to have you listed in our [ADOPTERS.md file](https://github.com/flyimg/flyimg/blob/main/ADOPTERS.md)!
Feel free to add your entry — we'd love to highlight your support.
Thank you!
