### ISSUE TITLE
Running without Docker

### ISSUE THREAD

**Issue by folkevil** [flyimg/flyimg#61]
Hi,
i'm trying to make flyimg running without Docker (replace with Apache, and htaccess rewrite) but no luck. Any suggestion ?

**Comment by sadok-f** [comment]
Hi @folkevil,
Thank you for submitting your issue.
In the current version, It's a bit hard to run Flyimg without Docker, you need a debian image with imagemagick, mozjpeg, webp, facedetection python... and other libraries installed and configured.
And that is the whole purpose of the project, avoid the mess.
